name: Os-IROSE
description: |
  Open Source R.O.S.E. Online server
version: 0.0.1# Version of the Catalog to be used
category: Game Servers
maintainer: RavenX8
license: Apache-2.0
projectURL: https://github.com/dev-osrose/osIROSE-new