version: "3"
services:
  base:
    environment:
      DB_HOST: ${mysql_hostname}
      DB_PORT: ${mysql_lb_port}
      DB_NAME: ${mysql_database}
      DB_USER_NAME: ${mysql_user}
      DB_USER_PASSWORD: ${mysql_password}
    tty: true
    stdin_open: true