version: "2"
services:
  base:
    image: busybox
    environment:
      DB_HOST: ${mysql_hostname}
      DB_PORT: ${mysql_lb_port}
      DB_NAME: ${mysql_database}
      DB_USER_NAME: ${mysql_user}
      DB_USER_PASSWORD: ${mysql_password}
    tty: true
    stdin_open: true
  node:
    image: ravenx8/osirose
    networks:
     - frontend
     - backend
    ports:
     - "29000:29000"
     - "29100:29100"
     - "29200:29200"
    volumes:
     - osirose-data:/data
     - osirose-logs:/logs
     - osirose-config:/config
    environment:
      - SERVER=NodeServer
  login:
    image: ravenx8/osirose
    networks:
     - backend
    ports:
     - "29000:29000"
     - "29010:29010"
    volumes:
     - osirose-data:/data
     - osirose-logs:/logs
     - osirose-config:/config
    extends:
      service: base
    environment:
      - SERVER=LoginServer
  char:
    image: ravenx8/osirose
    networks:
     - backend
    ports:
     - "29100:29100"
     - "29110:29110"
    volumes:
     - osirose-data:/data
     - osirose-logs:/logs
     - osirose-config:/config
    extends:
      service: base
    environment:
      - SERVER=CharServer
  map:
    image: ravenx8/osirose
    networks:
      - backend
    ports:
     - "29200:29200"
     - "29210:29210"
    volumes:
     - osirose-data:/data
     - osirose-logs:/logs
     - osirose-config:/config
    extends:
      service: base
    environment:
      - SERVER=MapServer
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: overlay