version: "2"
services:
  base:
    image: osirose-server
    environment:
      DB_HOST: ${mysql_hostname}
      DB_PORT: ${mysql_lb_port}
      DB_NAME: ${mysql_database}
      DB_USER_NAME: ${mysql_user}
      DB_USER_PASSWORD: ${mysql_password}
    tty: true
    stdin_open: true
  server-data:
    image: busybox
    labels:
     io.rancher.container.start_once: true
    volumes:
     - /data
     - /logs
     - /config
  node:
    image: osirose-server
    networks:
     - frontend
     - backend
    ports:
     - "29000:29000"
     - "29100:29100"
     - "29200:29200"
    volumes_from:
      - server-data
    environment:
      - SERVER=NodeServer
  login:
    image: osirose-server
    networks:
     - backend
    ports:
     - "29000:29000"
     - "29010:29010"
    volumes_from:
      - server-data
    extends:
      service: base
    environment:
      - SERVER=LoginServer
  char:
    image: osirose-server
    networks:
     - backend
    ports:
     - "29100:29100"
     - "29110:29110"
    volumes_from:
      - server-data
    extends:
      service: base
    environment:
      - SERVER=CharServer
  map:
    image: osirose-server
    networks:
      - backend
    ports:
     - "29200:29200"
     - "29210:29210"
    labels:
      io.rancher.sidekicks: server-data
    volumes_from:
      - server-data
    extends:
      service: base
    environment:
      - SERVER=MapServer
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: overlay